# roles/samba/vars/os_Debian.yml
---

setup_samba_packages:
  - samba-common
  - samba
  - samba-client

setup_samba_vfs_packages:  # not used ??
  - samba-vfs-modules

setup_samba_selinux_packages: []  # not used ??
setup_samba_selinux_booleans: []  # not used ??

setup_samba_configuration_dir: /etc/samba
setup_samba_configuration: "{{ setup_samba_configuration_dir }}/smb.conf"
setup_samba_username_map_file: "{{ setup_samba_configuration_dir }}/smbusers"

# The name of the Samba service in older releases (Ubuntu 14.04,
# Debian <8) is "samba".
setup_samba_services:
  - smbd
  - nmbd

setup_samba_www_documentroot: ""  # not used ??
