#################################################
# DO Community Playbooks: Initial Server Setup
#################################################
---
- name: Include default vars
  ansible.builtin.include_vars: "default.yml"

- name: Include samba vars
  ansible.builtin.include_vars: "samba.yml"

- name: Include OS specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "os_{{ ansible_distribution }}.yml"
    - "os_{{ ansible_os_family }}.yml"

# Install Packages
# - name: Update apt
#   ansible.builtin.apt:
#     state: update_cache=yes

- name: Install required system packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    # state: latest
    update_cache: true
  with_items: "{{ setup_samba_packages }}"

- name: Samba configuration
  ansible.builtin.template:
    dest: "{{ setup_samba_configuration }}"
    src: smb.conf.j2
    validate: 'testparm -s %s'
    mode: "0640"
  notify:
    - Restart Samba services
  tags: samba
