#################################################
# DO Community Playbooks: Initial Server Setup
# smbpasswd -a <user>
#################################################
---
- name: Setup localhost samba server
  hosts: localhost
  connection: local
  # vars_files:
  #   - vars/default.yml

  roles:
    - role: setup_samba
      vars:
        setup_samba_log: /var/log/samba/localShares
        setup_samba_guest_account: "nobody"
        setup_samba_create_user:
          - "{{ ansible_env.USER }}" # Add current user to samba by default
          - "@sambashare"  # Add user to sambashare group
